[package]
name = "recipient-typescript"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.15.1"
blake2b-ref = "0.3.0"
molecule = { version = "0.7.5", default-features = false }
force-bridge-types = { path = "../../types" }